CREATE TABLE IF NOT EXISTS messages (
  id TEXT PRIMARY KEY,
  role TEXT,
  content TEXT,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mcq_tests (
  id TEXT PRIMARY KEY,
  slug TEXT UNIQUE,
  data TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
